add spacing to sidebar collapsible sections to better distinguish bet…
revoltchat/revite pull request #254
Opened 2021-09-17 04:43 UTC by bdbch

This PR adds more spacing to sidebar categories to better distinguish between them when all are open.
It also includes an option to remove the spacing when needed.

Old:
![image](https://user-images.githubusercontent.com/6538827/133725725-733468d1-c216-446f-8405-de0e4ad74392.png)

New:
![image](https://user-images.githubusercontent.com/6538827/133725688-e2ea803a-b3d0-496a-8e94-4c40c11c4e8f.png)

2021-10-31 22:40 UTC, insertish requested changes
The 24px padding is a bit excessive, I think 12px would probably look nicer, there's just too much whitespace really.

2021-10-31 22:40 UTC, insertish commented on src/components/common/CollapsibleSection.tsx
> +            <Details
There could instead just be an option on `<Details />` such as `padTop` or something along those lines, instead of creating a whole new component.

2022-05-08 20:45 UTC, Rexogamer commented
Just checking in - are you still willing to work on this PR?

2022-07-07 22:19 UTC, Rexogamer commented
Closing due to inactivity - if you're still willing to work on this, feel free to reopen this/a new PR. Thanks!

2022-07-07 22:19 UTC, closed without merging