meta: add issue forms
revoltchat/revite pull request #414
Opened 2021-11-22 23:06 UTC by Rexogamer

apologies if there are any issues/errors or if this is the wrong repo, but related to revoltchat/revolt#208

2021-12-25 10:04 UTC, insertish requested changes
Apart from that it looks good but I would also include a way to include the commit hash (if possible) which is present in the settings menu.

2021-12-28 17:00 UTC, Rexogamer commented on .github/ISSUE_TEMPLATE/bug.yaml
> +  - insertish
I mean all issues are added to your project tracker, but fair enough

2022-01-04 11:01 UTC, insertish requested changes

2022-01-04 11:01 UTC, insertish commented on .github/ISSUE_TEMPLATE/bug.yaml
> +        - I'm using the PWA or Revolt Desktop
Asked for PWA further down, this loses specificity on browser.

2022-01-05 21:48 UTC, insertish approved these changes

2022-01-05 21:49 UTC, merged