Added button to invite to channel
revoltchat/revite pull request #420
Opened 2021-11-26 20:41 UTC by maxer137

Related to #38

I do not know if there's a "manage channel" view that we can navigate to. 
For now, I left the "manage channel" button commented out.

2021-12-03 21:47 UTC, Rexogamer commented
It seems `open_channel_settings` is the action in question (although instead of opening a popup it's a separate page (`channel/<id>/settings`)).

2021-12-03 22:26 UTC, Rexogamer requested changes
Here's the manage channel code. One thing I'd like to note is that it seems both of these buttons appear even if you lack the relevant perms, so some further debugging will be needed there.

2021-12-03 22:26 UTC, Rexogamer commented on src/components/navigation/items/ButtonItem.tsx
> +import { ChannelPermission } from "revolt.js/dist/api/permissions";
Imports:
```suggestion
import { X, Crown, UserPlus, Cog } from "@styled-icons/boxicons-regular";
import { observer } from "mobx-react-lite";
import { Link } from "react-router-dom";
import { Presence } from "revolt-api/types/Users";
import { ChannelPermission } from "revolt.js/dist/api/permissions";
import { Channel } from "revolt.js/dist/maps/Channels";
import { User } from "revolt.js/dist/maps/Users";
```

2021-12-03 22:26 UTC, Rexogamer commented on src/components/navigation/items/ButtonItem.tsx
> +                {/*)}*/}
Button code:
```suggestion
                {!isTouchscreenDevice &&
                    channel.channel_type === "TextChannel" &&
                    channel.permission & ChannelPermission.ManageChannel && (
                        <div className="actions">
                            <Link to={`/channel/${channel._id}/settings`}>
                                <IconButton>
                                    <Cog size={24} />
                                </IconButton>
                            </Link>
                        </div>
                    )
                }
```

2021-12-06 16:26 UTC, maxer137 commented
> Here's the manage channel code. One thing I'd like to note is that it seems both of these buttons appear even if you lack the relevant perms, so some further debugging will be needed there.

I haven't been able to reproduce this. For me, the buttons only show up when you have the right permissions.

2022-01-06 00:15 UTC, ryanalexander commented
@maxer137 are you still working on this? If not i will happily take over the feature

2022-05-26 22:33 UTC, Rexogamer commented
Just checking in - do you still want to work on this?

2022-09-19 08:25 UTC, closed without merging