feat: add "join server" modal
revoltchat/revite pull request #475
Opened 2021-12-29 23:58 UTC by Rexogamer

replacing #468, which was closed due to a branch move

fixes #436
fixes #102

2022-01-04 11:00 UTC, insertish requested changes

2022-01-04 11:00 UTC, insertish commented on src/context/intermediate/modals/Input.tsx
> +                        await client.joinInvite(code);
Should probably open the server after joining, although for this the logic from the invite page and embed should be combined and also used here.

2022-01-04 13:38 UTC, Rexogamer commented on src/context/intermediate/modals/Input.tsx
> +                            console.log("Something went wrong.");
I did attempt this, will try again

2022-01-05 22:04 UTC, insertish commented on src/context/intermediate/modals/Input.tsx
> +                            console.log("Something went wrong.");
(any errors thrown here should be caught by the modal and displayed)

2023-01-24 18:00 UTC, insertish commented
Closing due to rewrite, https://github.com/revoltchat/frontend.
We should make this from the get-go with the new client.

2023-01-24 18:00 UTC, closed without merging