fix: delete gigachad
revoltchat/revite pull request #929
Opened 2023-08-22 13:25 UTC by sussycatgirl

## Please make sure to check the following tasks before opening and submitting a PR

* [ ] I understand and have followed the [contribution guide](https://github.com/revoltchat/revolt/discussions/282)
* [ ] I have tested my changes locally and they are working as intended
* [ ] These changes do not have any notable side effects on other Revolt projects
* [ ] (optional) I have opened a pull request on [the translation repository](https://github.com/revoltchat/translations)
* [ ] I have included screenshots to demonstrate my changes

2023-08-22 13:27 UTC, infi approved these changes
Does whats intended with the PR.

2023-08-22 13:28 UTC, Rexogamer approved these changes
LGTM

2023-08-22 13:31 UTC, SingleSlice commented
Looks good to me

2023-08-22 13:31 UTC, amycatgirl commented
looks good to me as well

2023-08-22 13:31 UTC, tulpenkiste commented
LGTM :trollface:

2023-08-22 13:33 UTC, lo-kiss commented
LGTM

2023-08-22 13:33 UTC, NyaomiDEV commented
lgtm

2023-08-22 13:49 UTC, insertish requested changes

2023-08-22 13:49 UTC, insertish commented on src/assets/emojis.ts
> -        gigachad: "custom:gigachad.webp",
Remove these two changes and it'll be ready to merge.

2023-08-22 13:49 UTC, insertish commented on src/assets/emojis.ts
> -        gigachad: "custom:gigachad.webp",
Other than that LGTM

2023-08-23 10:11 UTC, drendog approved these changes

2023-08-25 05:08 UTC, Zomatree commented
🇹🇩

2023-08-25 05:52 UTC, searinminecraft commented
eh... looks good to me

2023-08-30 17:51 UTC, Rexogamer commented
> 

gigaromania

2023-08-30 17:52 UTC, Rexogamer commented
> giga🇹🇩

gigaromania

2024-07-31 10:37 UTC, insertish commented
Fixed in 9eca58dda18e6f7fe401d4b9cdd482d3dce3d788

2024-07-31 10:37 UTC, closed without merging

2024-07-31 18:46 UTC, amycatgirl commented
holy fuck he did it